name: Assignment 3 Testing with Jest

on: 
  pull_request:
    branches:
      - master
      - feedback
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM dependencies
        run: npm install
      - name: Run jest tests for tests
        run: npm run test
