import Head from 'next/head'
import Image from 'next/image'

// Our Imports.
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Example from '../components/Example'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* 
          The Following line will only install Roboto on this page.
          Later in the course we'll learn about the "document.js"
          page where this will be more appropriate.
         */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Example />
        <Container maxWidth="md">
          <Box sx={{ my: 4 }}>
            <Typography variant="h2" component="h2" color="primary.main">
              MUI Example
            </Typography>
            <Typography variant="p" component="p" color="secondary">
              You can perhaps see why this is a popular package.
            </Typography>
          </Box>
        </Container>
        <Example />
      </main>
    </div>
  )
}
