//https://api.quotable.io/random

//https://example.com/comments/1

# POST https://example.com/comments/1 HTTP/1.1
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }

https://dog-api.kinduff.com/api/facts