import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import NavBar from '@components/NavBar';

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar />
        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">
          <Typography variant="h3">
            Robbin Route
          </Typography>
          <Typography variant="p">
            Hey this is so fun.
          </Typography>
        </Container>
    </div>
  )
}
