import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// our custom components
import Hello from '../components/Hello'
import NewConcept from '../components/NewConcept'
import ComponentWrapper from '../components/ComponentWrapper'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 >
          Fundamentals Components Example
        </h1>
        <ComponentWrapper textColor={"blue"}>
          <Hello />
          <NewConcept concept={"how to import components"} />
          <NewConcept concept={"how to use props in a component"} />
          <NewConcept concept={"how to import components"} />
        </ComponentWrapper>
      </main>

    </div>
  )
}
