import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// our custom components
import {Hello1} from '../components/Hello'
import {Hello2} from '../components/Hello'
import {Hello3} from '../components/Hello'
import {NewConcept1} from '../components/NewConcept'
import {NewConcept2} from '../components/NewConcept'
import ComponentWrapper from '../components/ComponentWrapper'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 >
          Fundamentals Components Example
        </h1>
        <Hello1 />
        <Hello2 />
        <Hello3 />
        <NewConcept1 concept={"how to import components"} textColor={"green"} />
        <NewConcept2 concept={"how to use props in a component"} textColor={"purple"} />
        <ComponentWrapper textColor={"blue"}>
          <h4>Just a random h4</h4>
          <Hello1 />
          <NewConcept1 concept={"how to have fun"} textColor={"red"} />
        </ComponentWrapper>
      </main>

    </div>
  )
}
