import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

// our custom components
import {Hello1, Hello2, Hello3} from '../components/Hello'
import {NewConcept1, NewConcept2} from '../components/NewConcept'
import ComponentWrapper from '../components/ComponentWrapper'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 >
          Welcome to Next/React
        </h1>
        <Hello1 />
        <Hello2 />
        <Hello3 />
        <NewConcept1 concept={"how to import components"} textColor={"green"} />
        <NewConcept2 concept={"how to use props in a component"} textColor={"purple"} />
        <ComponentWrapper textColor={"blue"}>
          <h4>Just a random h4</h4>
          <Hello1 />
          <NewConcept1 concept={"how to have fun"} textColor={"red"} />
        </ComponentWrapper>
      </main>
    </>
  )
}
