export const MOVIE_LIST = [
    {"name":"The Shawshank Redemption", "year": 1994 },
    {"name":"The Godfather", "year": 1972 },
    {"name":"The Dark Knight", "year": 2008 },
    {"name":"The Godfather: Part II", "year": 1974 },
    {"name":"The Lord of the Rings: The Return of the King", "year": 2003 },
    {"name":"Pulp Fiction", "year": 1994 },
    {"name":"Schindler's List", "year": 1993 },
    {"name":"12 Angry Men", "year": 1957 },
    {"name":"Inception", "year": 2010 },
    {"name":"Fight Club", "year": 1999 },
    {"name":"The Lord of the Rings: The Fellowship of the Ring", "year": 2001 },
    {"name":"Forrest Gump", "year": 1994 },
    {"name":"The Good, the Bad and the Ugly", "year": 1966 },
    {"name":"Hamilton", "year": 2020 },
    {"name":"The Lord of the Rings: The Two Towers", "year": 2002 },
    {"name":"The Matrix", "year": 1999 },
    {"name":"Goodfellas", "year": 1990 },
    {"name":"Star Wars: Episode V - The Empire Strikes Back", "year": 1980 },
    {"name":"One Flew Over the Cuckoo's Nest", "year": 1975 },
    {"name":"Parasite", "year": 2019 },
    {"name":"Interstellar", "year": 2014 },
    {"name":"City of God", "year": 2002 },
    {"name":"Spirited Away", "year": 2001 },
    {"name":"Saving Private Ryan", "year": 1998 },
    {"name":"The Green Mile", "year": 1999 },
    {"name":"Life Is Beautiful", "year": 1997 },
    {"name":"Se7en", "year": 1995 },
    {"name":"The Silence of the Lambs", "year": 1991 },
    {"name":"Star Wars: Episode IV - A New Hope", "year": 1977 },
    {"name":"Harakiri", "year": 1962 },
    {"name":"Seven Samurai", "year": 1954 },
    {"name":"It's a Wonderful Life", "year": 1946 },
    {"name":"Joker", "year": 2019 },
    {"name":"Whiplash", "year": 2014 },
    {"name":"The Intouchables", "year": 2011 },
    {"name":"The Prestige", "year": 2006 },
    {"name":"The Departed", "year": 2006 },
    {"name":"The Pianist", "year": 2002 },
    {"name":"Gladiator", "year": 2000 },
    {"name":"American History X", "year": 1998 },
    {"name":"The Usual Suspects", "year": 1995 },
    {"name":"LÃ©on: The Professional", "year": 1994 },
    {"name":"The Lion King", "year": 1994 },
    {"name":"Terminator 2: Judgment Day", "year": 1991 },
    {"name":"Cinema Paradiso", "year": 1988 },
    {"name":"Grave of the Fireflies", "year": 1988 },
    {"name":"Back to the Future", "year": 1985 },
    {"name":"Anand", "year": 1971 },
    {"name":"Once Upon a Time in the West", "year": 1968 },
    {"name":"Psycho", "year": 1960 },
    {"name":"Casablanca", "year": 1942 },
    {"name":"Modern Times", "year": 1936 },
    {"name":"City Lights", "year": 1931 },
    {"name":"Capernaum", "year": 2018 },
    {"name":"Ayla: The Daughter of War", "year": 2017 },
    {"name":"Your Name.", "year": 2016 },
    {"name":"Dangal", "year": 2016 },
    {"name":"Spider-Man: Into the Spider-Verse", "year": 2018 },
    {"name":"Avengers: Endgame", "year": 2019 },
    {"name":"Avengers: Infinity War", "year": 2018 },
    {"name":"Coco (I)", "year": 2017 },
    {"name":"Django Unchained", "year": 2012 },
    {"name":"The Dark Knight Rises", "year": 2012 },
    {"name":"3 Idiots", "year": 2009 },
    {"name":"Like Stars on Earth", "year": 2007 },
    {"name":"WALLÂ·E", "year": 2008 },
    {"name":"The Lives of Others", "year": 2006 },
    {"name":"Oldboy", "year": 2003 },
    {"name":"Memento", "year": 2000 },
    {"name":"Princess Mononoke", "year": 1997 },
    {"name":"Once Upon a Time in America", "year": 1984 },
    {"name":"Raiders of the Lost Ark", "year": 1981 },
    {"name":"The Shining", "year": 1980 },
    {"name":"Apocalypse Now", "year": 1979 },
    {"name":"Alien", "year": 1979 },
    {"name":"High and Low", "year": 1963 },
    {"name":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", "year": 1964 },
    {"name":"Witness for the Prosecution", "year": 1957 },
    {"name":"Paths of Glory", "year": 1957 },
    {"name":"Rear Window", "year": 1954 },
    {"name":"Sunset Blvd.", "year": 1950 },
    {"name":"The Great Dictator", "year": 1940 },
    {"name":"1917", "year": 2019 },
    {"name":"Uri: The Surgical Strike", "year": 2019 },
    {"name":"Tumbbad", "year": 2018 },
    {"name":"Andhadhun", "year": 2018 },
    {"name":"Drishyam", "year": 2013 },
    {"name":"The Hunt", "year": 2012 },
    {"name":"A Separation", "year": 2011 },
    {"name":"Incendies", "year": 2010 },
    {"name":"7 Kogustaki Mucize", "year": 2019 },
    {"name":"My Father and My Son", "year": 2005 },
    {"name":"Toy Story 3", "year": 2010 },
    {"name":"Inglourious Basterds", "year": 2009 },
    {"name":"Eternal Sunshine of the Spotless Mind", "year": 2004 },
    {"name":"AmÃ©lie", "year": 2001 },
    {"name":"Snatch", "year": 2000 },
    {"name":"Requiem for a Dream", "year": 2000 },
    {"name":"American Beauty", "year": 1999 },
    {"name":"Good Will Hunting", "year": 1997 },
]
